### ISSUE TITLE
How would I write code to press a key or number of keys programmatically and generate the sound(s)?

### ISSUE THREAD

**Issue by Shinehah-Gnolaum** [AudioKit/ROMPlayer#3]
How would I write code to press a key or number of keys programmatically and generate the sound(s)?

**Comment by analogcode** [comment]
Hi @Shinehah-Gnolaum,

There's a few ways. 

- You could call the "conductor.playNote" methods directly.
- You could use MIDI files. There is an example of that already in the code (midiLoad and playSequencer in the Conductor class)
- You could create sequences via code using something like the AKSequencer (https://audiokitpro.com/get-the-most-out-of-your-aksequencer/)

Good luck!

**Comment by analogcode** [comment]
And, to press the a key on the onscreen keyboard and sound a note, call

keyboardView.pressAdded(noteNumber, velocity: velocity)

In the ParentController
