### ISSUE TITLE
No sound - missing aif files?

### ISSUE THREAD

**Issue by TheHmmka** [AudioKit/ROMPlayer#4]
Just checkout and run on my iPad - no sound... =(
UPD:
Presets contains aif files, but there are no aif files in the project.

**Comment by aure** [comment]
I'm curious if there was no sound or no sound and also an error message.

**Comment by TheHmmka** [comment]
> I'm curious if there was no sound or no sound and also an error message.

Just figure out that example has no aif files and don't know about error.
