### ISSUE TITLE
Memory Leaks

### ISSUE THREAD

**Issue by daniv3r** [AudioKit/ROMPlayer#6]
Hi!
I don't know if it's me or if i found some kind of issue.
So I use sound part of ParentViewController and all "AudioSystem" in my app

There are problems in 
 1)PianoGame.Fatten.init(AudioKit.AKNode) -> PianoGame.Fatten : 
 pannedSource = AKPanner(inputMixer, pan: -1)
PianoGame.Conductor.init() -> PianoGame.Conductor
fatten = Fatten(autoPanMixer)

2)PianoGame.PingPongDelay.init(AudioKit.AKNode) -> PianoGame.PingPongDelay
    var leftDelay = AKVariableDelay()
 PianoGame.Conductor.init() -> PianoGame.Conductor
        multiDelay = PingPongDelay(fatten)

3)PianoGame.Conductor.init() -> PianoGame.Conductor    
    tremolo = AKTremolo(sampler1, waveform: AKTable(.sine))
4)PianoGame.AutoPan.init(AudioKit.AKNode) -> PianoGame.AutoPan
        output = AKOperationEffect(input) { input, parameters in

5)PianoGame.FilterSection.init(AudioKit.AKNode) -> PianoGame.FilterSection
        output = AKOperationEffect(input) { input, parameters in
6)    var leftCompensator = AKVariableDelay()

and etc

<img width="224" alt="Снимок экрана 2019-05-27 в 12 35 18" src="https://user-images.githubusercontent.com/33792509/58411155-557bfd80-807c-11e9-96d7-2cbf51090874.png">
<img width="1011" alt="Снимок экрана 2019-05-27 в 12 35 43" src="https://user-images.githubusercontent.com/33792509/58411159-557bfd80-807c-11e9-844c-c2948a819b2c.png">

**Comment by PaulBatchelor** [comment]
These all look soundpipe/sporth related to me. Maybe their destroy functions aren't being called?

**Comment by daniv3r** [comment]
I don't know,but leaks appear when screen loaded/appear with initializing of these properties @PaulBatchelor

**Comment by colinhallett** [comment]
I have a similar problem I think - see https://github.com/colinhallett/MemoryLeakTest

**Comment by aure** [comment]
Since this is an AudioKit issue, not specifically ROMPlayer, I am going to close it.
