### ISSUE TITLE
Linux port [Tracker]

### ISSUE THREAD

**Issue by RarogCmex** [AudioKit/ROMPlayer#7]
Ok, I'd liked it, but Is it possible to port ones to Linux? 
Any ideas? 
I have no time for do it youself currently... But I'll do it.

**Comment by analogcode** [comment]
This might be a good question for @getdunne. His AKSampler code may be portable. Though the UI will need to be re-done.

**Comment by getdunne** [comment]
AKSampler should be fully portable. AudioKit is mainly about making DSP code written in C/C++ accessible from Swift programs (which are very macOS/iOS-specific). Most of the core DSP code was ported over from Unix/Linux. AKSampler is a rare exception. If you really want to port it, you should probably just wrap it as an LV2 plug-in, but you should probably look at what exists already, e.g. [the LinuxSampler project](https://www.linuxsampler.org/).
