### ISSUE TITLE
Is midi keyboard input supported?

### ISSUE THREAD

**Issue by zhouhao27** [AudioKit/ROMPlayer#9]
I'd like to check if the midi keyboard supported? How to enable it?

**Comment by aure** [comment]
its supported and ebabled.

**Comment by zhouhao27** [comment]
Only one method (`receivedMIDISetupChange`)  for `AKMIDIListener` was called. Other methods in this delegates are not triggered at all.

But all works in `SynthOne`. Any hints? Thanks.

**Comment by sieren** [comment]
@aure any chance this is the same thing I ran into recently when basing S1 onto a newer AK version?
@zhouhao27 i suspect the delegate method names have changed in AudioKit and this hasn't been reflected in the code here.

**Comment by aure** [comment]
Thanks @sieren of course you are right, I've made the fix.
